create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_queue (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_id text not null,
  title text not null,
  body text not null,
  send_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending','sent','cancelled','failed')),
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notification_queue_pending_idx
  on public.notification_queue(status, send_at);

alter table public.push_subscriptions enable row level security;
alter table public.notification_queue enable row level security;

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions"
  on public.push_subscriptions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "users manage own notification queue" on public.notification_queue;
create policy "users manage own notification queue"
  on public.notification_queue for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
